### ISSUE TITLE
Добавить настройки имен основных полей заказа

### ISSUE THREAD

**Issue by mnoskov** [evocms-community/commerce#37]
Нужна возможность задать имена полей для вместо name, phone, email. Чтобы можно было, например, использовать вместо name - fio, и т.п.
Также нужна возможность указать email покупателя по-умолчанию, использовать его если email не в заказе пустой.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/100_%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B8_%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2_%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F%D0%BC%D0%B8.md#contentfields - такое хочешь сделать? 

https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/core/controller/Content.php#L242

**Comment by mnoskov** [comment]
Да, типа того

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/020_Параметры.md#fieldaliases

**Comment by Pathologic** [comment]
Первое решается параметром fieldAliases, второе - defaultsSources или через prepare https://docs.evo.im/04_extras/formlister/020_parametry.html.
